/*
 * File: app/store/JsonStoreSiswa.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SistemInformasiNilai.store.JsonStoreSiswa', {
    extend: 'Ext.data.Store',

    requires: [
        'SistemInformasiNilai.model.modelSiswa',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'SistemInformasiNilai.model.modelSiswa',
            storeId: 'JsonStoreSiswa',
            pageSize: 25,
            proxy: {
                type: 'ajax',
                api: {
                    read: 'api/siswa/dataSiswa.php'
                },
                reader: {
                    type: 'json',
                    root: 'data'
                }
            },
            listeners: {
                beforeload: {
                    fn: me.onJsonStoreSiswaBeforeLoad,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onJsonStoreSiswaBeforeLoad: function(store, operation, eOpts) {
        var namaSiswa = Ext.ComponentQuery.query('#srcNamaSiswa')[0].getValue();
        var kelasSiswa = Ext.ComponentQuery.query('#srcKelasSiswa')[0].getValue();

        store.getProxy().setExtraParam('NamaSiswa_', namaSiswa);
        store.getProxy().setExtraParam('KelasSiswa_', kelasSiswa);

        Ext.ComponentQuery.query('#tabelSiswa')[0].getSelectionModel().clearSelections();
        Ext.ComponentQuery.query('#btnEditSiswa')[0].setDisabled(true);
        Ext.ComponentQuery.query('#btnHapusSiswa')[0].setDisabled(true);
    }

});