/*
 * File: app/store/JsonStoreNilai.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SistemInformasiNilai.store.JsonStoreNilai', {
    extend: 'Ext.data.Store',

    requires: [
        'SistemInformasiNilai.model.modelNilai',
        'Ext.data.proxy.Ajax',
        'Ext.data.reader.Json'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            model: 'SistemInformasiNilai.model.modelNilai',
            storeId: 'JsonStoreNilai',
            pageSize: 25,
            proxy: {
                type: 'ajax',
                api: {
                    read: 'api/nilai/dataNilai.php'
                },
                reader: {
                    type: 'json',
                    root: 'data'
                }
            },
            listeners: {
                beforeload: {
                    fn: me.onJsonstoreBeforeLoad,
                    scope: me
                }
            }
        }, cfg)]);
    },

    onJsonstoreBeforeLoad: function(store, operation, eOpts) {
        var namaSiswa = Ext.ComponentQuery.query('#srcNamaNilai')[0].getValue();
        var kelasSiswa = Ext.ComponentQuery.query('#srcKelasNilai')[0].getValue();
        var mapelNilai = Ext.ComponentQuery.query('#srcMapelNilai')[0].getValue();
        var semesterNilai = Ext.ComponentQuery.query('#srcSemesterNilai')[0].getValue();

        store.getProxy().setExtraParam('NamaSiswa_', namaSiswa);
        store.getProxy().setExtraParam('KelasSiswa_', kelasSiswa);
        store.getProxy().setExtraParam('MapelNilai_', mapelNilai);
        store.getProxy().setExtraParam('SemesterNilai_', semesterNilai);

        Ext.ComponentQuery.query('#tabelNilai')[0].getSelectionModel().clearSelections();
        Ext.ComponentQuery.query('#btnEditNilai')[0].setDisabled(true);
        Ext.ComponentQuery.query('#btnHapusNilai')[0].setDisabled(true);
    }

});