/*
 * File: app/view/MainView.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SistemInformasiNilai.view.MainView', {
    extend: 'Ext.container.Viewport',
    alias: 'widget.mainview',

    requires: [
        'Ext.Img',
        'Ext.menu.Menu',
        'Ext.menu.Item',
        'Ext.form.Label',
        'Ext.chart.Chart',
        'Ext.util.Point',
        'Ext.chart.series.Pie',
        'Ext.chart.Legend',
        'Ext.chart.axis.Category',
        'Ext.chart.axis.Numeric',
        'Ext.button.Button',
        'Ext.grid.Panel',
        'Ext.grid.View',
        'Ext.chart.series.Column',
        'Ext.form.field.ComboBox',
        'Ext.grid.column.Date',
        'Ext.toolbar.Paging'
    ],

    itemId: 'mainView',
    layout: 'border',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'panel',
                    region: 'west',
                    split: true,
                    itemId: 'menuPanel',
                    width: 150,
                    bodyCls: 'background',
                    title: '',
                    items: [
                        {
                            xtype: 'image',
                            height: 80,
                            margin: '10 0 10 10',
                            src: 'icon/logokemenperin2.png'
                        },
                        {
                            xtype: 'menu',
                            cls: 'background-menu',
                            floating: false,
                            itemId: 'menu',
                            bodyCls: 'background',
                            items: [
                                {
                                    xtype: 'menuitem',
                                    itemId: 'home',
                                    text: 'Home'
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'nilai',
                                    text: 'Nilai'
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'siswa',
                                    text: 'Siswa'
                                },
                                {
                                    xtype: 'menuitem',
                                    itemId: 'kelasjur',
                                    text: 'Kelas & Jurusan'
                                }
                            ],
                            listeners: {
                                click: {
                                    fn: me.onMenuClick,
                                    scope: me
                                }
                            }
                        }
                    ]
                },
                {
                    xtype: 'panel',
                    region: 'center',
                    itemId: 'contentPanel',
                    layout: 'card',
                    items: [
                        {
                            xtype: 'panel',
                            itemId: 'homePanel',
                            bodyCls: 'background',
                            items: [
                                {
                                    xtype: 'container',
                                    cls: 'title-page',
                                    height: 90,
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            margins: '0, 0, 0, 10',
                                            cls: 'title-text',
                                            text: 'HOME'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    height: '38%',
                                    margin: '50, 0, 0, 20',
                                    width: '95%',
                                    layout: 'hbox',
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 0,
                                            height: 300,
                                            width: '50%',
                                            layout: {
                                                type: 'hbox',
                                                align: 'middle',
                                                pack: 'center'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    height: '100%',
                                                    width: '50%',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'center',
                                                        pack: 'center'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'container',
                                                            flex: 1,
                                                            margins: '5, 5, 5, 5',
                                                            height: '50%',
                                                            style: '{\nbackground: #5ac8fa;\n}',
                                                            width: '100%',
                                                            layout: {
                                                                type: 'vbox',
                                                                align: 'center'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'label',
                                                                    flex: 1,
                                                                    margins: '10, 0, 0, 0',
                                                                    cls: 'font-dashboard',
                                                                    maxHeight: 30,
                                                                    text: 'KELAS'
                                                                },
                                                                {
                                                                    xtype: 'label',
                                                                    flex: 1,
                                                                    margins: '10, 0, 0, 0',
                                                                    cls: 'font-dashboard-value',
                                                                    componentCls: 'font-dashboard-value',
                                                                    itemId: 'txtValueKelas',
                                                                    text: '0'
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            flex: 1,
                                                            margins: '5, 5, 5, 5',
                                                            height: '50%',
                                                            style: '{\nbackground: #ff2d55;\n}',
                                                            width: '100%',
                                                            layout: {
                                                                type: 'vbox',
                                                                align: 'center'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'label',
                                                                    flex: 1,
                                                                    margins: '10, 0, 0, 0',
                                                                    cls: 'font-dashboard',
                                                                    componentCls: 'font-dashboard',
                                                                    maxHeight: 30,
                                                                    text: 'MATA PELAJARAN'
                                                                },
                                                                {
                                                                    xtype: 'label',
                                                                    flex: 1,
                                                                    margins: '10, 0, 0, 0',
                                                                    cls: 'font-dashboard-value',
                                                                    componentCls: 'font-dashboard-value',
                                                                    itemId: 'txtValueMapel',
                                                                    text: '0'
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    height: '100%',
                                                    width: '50%',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'center',
                                                        pack: 'center'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'container',
                                                            flex: 1,
                                                            margins: '5, 5, 5, 5',
                                                            height: '50%',
                                                            style: '{\nbackground: #ffcc00;\n}',
                                                            width: '100%',
                                                            layout: {
                                                                type: 'vbox',
                                                                align: 'center'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'label',
                                                                    flex: 1,
                                                                    margins: '10, 0, 0, 0',
                                                                    cls: 'font-dashboard',
                                                                    componentCls: 'font-dashboard',
                                                                    maxHeight: 30,
                                                                    text: 'JURUSAN'
                                                                },
                                                                {
                                                                    xtype: 'label',
                                                                    flex: 1,
                                                                    margins: '10, 0, 0, 0',
                                                                    cls: 'font-dashboard-value',
                                                                    componentCls: 'font-dashboard-value',
                                                                    itemId: 'txtValueJurusan',
                                                                    text: '0'
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'container',
                                                            flex: 1,
                                                            margins: '5, 5, 5, 5',
                                                            height: '50%',
                                                            style: '{\nbackground: #4cd964;\n}',
                                                            width: '100%',
                                                            layout: {
                                                                type: 'vbox',
                                                                align: 'center'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'label',
                                                                    flex: 1,
                                                                    margins: '10, 0, 0, 0',
                                                                    cls: 'font-dashboard',
                                                                    componentCls: 'font-dashboard',
                                                                    maxHeight: 30,
                                                                    text: 'SISWA'
                                                                },
                                                                {
                                                                    xtype: 'label',
                                                                    flex: 1,
                                                                    margins: '10, 0, 0, 0',
                                                                    cls: 'font-dashboard-value',
                                                                    componentCls: 'font-dashboard-value',
                                                                    itemId: 'txtValueSiswa',
                                                                    text: '0'
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 0,
                                            height: 300,
                                            width: '50%',
                                            layout: {
                                                type: 'hbox',
                                                pack: 'center'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    flex: 0,
                                                    height: '100%',
                                                    width: '50%',
                                                    layout: {
                                                        type: 'vbox',
                                                        align: 'center',
                                                        pack: 'center'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'chart',
                                                            margins: '5, 5, 5, 5',
                                                            height: 300,
                                                            hidden: true,
                                                            hideMode: 'offsets',
                                                            width: 300,
                                                            animate: true,
                                                            insetPadding: 20,
                                                            store: 'StoreChartPie',
                                                            theme: 'Category1',
                                                            series: [
                                                                {
                                                                    type: 'pie',
                                                                    label: {
                                                                        field: 'Label_',
                                                                        renderer: function(value, label, storeItem) {
                                                                    return '';
                                                                    },
                                                                        display: 'rotate',
                                                                        contrast: true,
                                                                        font: '12px Arial'
                                                                    },
                                                                    showInLegend: true,
                                                                    angleField: 'Jumlah_'
                                                                }
                                                            ],
                                                            legend: {
                                                                position: 'left'
                                                            }
                                                        },
                                                        {
                                                            xtype: 'chart',
                                                            height: 300,
                                                            width: 300,
                                                            shadow: true,
                                                            animate: true,
                                                            insetPadding: 20,
                                                            store: 'StoreChartPie',
                                                            theme: 'Category3',
                                                            axes: [
                                                                {
                                                                    type: 'Category',
                                                                    fields: [
                                                                        'Label_'
                                                                    ],
                                                                    position: 'left'
                                                                },
                                                                {
                                                                    type: 'Numeric',
                                                                    fields: [
                                                                        'Jumlah_'
                                                                    ],
                                                                    position: 'bottom'
                                                                }
                                                            ],
                                                            series: [
                                                                {
                                                                    type: 'bar',
                                                                    axis: 'bottom',
                                                                    xField: 'Jumlah_',
                                                                    yField: 'Jumlah_',
                                                                    stacked: true
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    height: '100%',
                                                    width: '50%',
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle',
                                                        pack: 'center'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'container',
                                                            flex: 1,
                                                            maxWidth: 90,
                                                            layout: {
                                                                type: 'vbox',
                                                                align: 'stretch',
                                                                pack: 'center'
                                                            },
                                                            items: [
                                                                {
                                                                    xtype: 'button',
                                                                    flex: 1,
                                                                    margins: '10, 10, 10, 10',
                                                                    cls: 'btnRefresh',
                                                                    itemId: 'btnRefreshMapel',
                                                                    maxHeight: 30,
                                                                    maxWidth: 100,
                                                                    text: 'Refresh'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    flex: 1,
                                                                    margins: '10, 10, 10, 10',
                                                                    cls: 'btnTambah',
                                                                    itemId: 'btnTambahMapel',
                                                                    maxHeight: 30,
                                                                    maxWidth: 100,
                                                                    text: 'Tambah'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    flex: 1,
                                                                    margins: '10, 10, 10, 10',
                                                                    cls: 'btnEdit',
                                                                    disabled: true,
                                                                    itemId: 'btnEditMapel',
                                                                    maxHeight: 30,
                                                                    maxWidth: 100,
                                                                    text: 'Edit'
                                                                },
                                                                {
                                                                    xtype: 'button',
                                                                    flex: 1,
                                                                    margins: '10, 10, 10, 10',
                                                                    cls: 'btnHapus',
                                                                    disabled: true,
                                                                    itemId: 'btnHapusMapel',
                                                                    maxHeight: 30,
                                                                    maxWidth: 100,
                                                                    text: 'Hapus'
                                                                }
                                                            ]
                                                        },
                                                        {
                                                            xtype: 'gridpanel',
                                                            flex: 1,
                                                            height: '100%',
                                                            itemId: 'tabelMapel',
                                                            margin: '5, 5, 5, 5',
                                                            autoScroll: true,
                                                            title: '',
                                                            scroll: 'vertical',
                                                            store: 'JsonStoreMapel',
                                                            columns: [
                                                                {
                                                                    xtype: 'gridcolumn',
                                                                    width: '75%',
                                                                    dataIndex: 'NamaMapel_',
                                                                    text: 'Mata pelajaran'
                                                                },
                                                                {
                                                                    xtype: 'gridcolumn',
                                                                    width: '25%',
                                                                    dataIndex: 'Kkm_',
                                                                    text: 'KKM'
                                                                }
                                                            ],
                                                            viewConfig: {
                                                                itemId: 'GridViewMapel'
                                                            }
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    height: '40%',
                                    margin: '30, 0, 0, 20',
                                    width: '95%',
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'chart',
                                            height: 250,
                                            width: '100%',
                                            shadow: true,
                                            animate: true,
                                            insetPadding: 20,
                                            store: 'StoreChartColumn',
                                            theme: 'Category6',
                                            axes: [
                                                {
                                                    type: 'Category',
                                                    fields: [
                                                        'Label_'
                                                    ],
                                                    position: 'bottom'
                                                },
                                                {
                                                    type: 'Numeric',
                                                    fields: [
                                                        'Jumlah_'
                                                    ],
                                                    position: 'left'
                                                }
                                            ],
                                            series: [
                                                {
                                                    type: 'column',
                                                    label: {
                                                        display: 'insideEnd',
                                                        field: '',
                                                        color: '#333',
                                                        'text-anchor': 'middle'
                                                    },
                                                    xField: 'Jumlah_',
                                                    yField: 'Jumlah_'
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'nilaiPanel',
                            autoScroll: true,
                            bodyCls: 'background',
                            title: '',
                            items: [
                                {
                                    xtype: 'container',
                                    cls: 'title-page',
                                    height: 90,
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            margins: '0, 0, 0, 10',
                                            cls: 'title-text',
                                            text: 'NILAI'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    margin: '20, 0, 0, 0',
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            margins: '10, 10, 10, 10',
                                            cls: 'btnTambah',
                                            itemId: 'btnTambahNilai',
                                            maxWidth: 100,
                                            text: 'Tambah'
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            margins: '10, 10, 10, 10',
                                            cls: 'btnEdit',
                                            disabled: true,
                                            itemId: 'btnEditNilai',
                                            maxWidth: 100,
                                            text: 'Edit'
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            margins: '10, 10, 10, 10',
                                            cls: 'btnHapus',
                                            disabled: true,
                                            itemId: 'btnHapusNilai',
                                            maxWidth: 100,
                                            text: 'Hapus'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    margin: '20, 0, 0, 0',
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            margins: '10, 10, 10, 10',
                                            cls: 'btnRefresh',
                                            itemId: 'btnRefreshNilai',
                                            maxWidth: 100,
                                            minWidth: 100,
                                            text: 'Refresh'
                                        },
                                        {
                                            xtype: 'textfield',
                                            margins: '10, 10, 10, 10',
                                            itemId: 'srcNamaNilai',
                                            fieldLabel: 'Nama',
                                            labelWidth: 45
                                        },
                                        {
                                            xtype: 'combobox',
                                            margins: '10, 10, 10, 0',
                                            itemId: 'srcKelasNilai',
                                            fieldLabel: 'Kelas',
                                            labelWidth: 40,
                                            emptyText: 'Pilih Kelas',
                                            editable: false,
                                            displayField: 'NamaKelas_',
                                            store: 'JsonStoreKelas',
                                            valueField: 'IDKelas_'
                                        },
                                        {
                                            xtype: 'combobox',
                                            margins: '10, 10, 10, 0',
                                            itemId: 'srcMapelNilai',
                                            fieldLabel: 'Mata Pelajaran',
                                            labelWidth: 110,
                                            emptyText: 'Pilih Mata Pelajaran',
                                            editable: false,
                                            displayField: 'NamaMapel_',
                                            store: 'JsonStoreMapel',
                                            valueField: 'IDMapel_'
                                        },
                                        {
                                            xtype: 'combobox',
                                            flex: 0,
                                            margins: '10, 10, 10, 0',
                                            itemId: 'srcSemesterNilai',
                                            maxWidth: 120,
                                            fieldLabel: 'Semester',
                                            labelWidth: 70,
                                            emptyText: '-',
                                            editable: false,
                                            displayField: 'Semester_',
                                            queryMode: 'local',
                                            store: 'JsonStoreSemester',
                                            valueField: 'Semester_'
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            margins: '10, 10, 10, 10',
                                            cls: 'btnCetak',
                                            itemId: 'btnCetakNilai',
                                            maxWidth: 100,
                                            minWidth: 100,
                                            text: 'Cetak'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    itemId: 'tabelNilai',
                                    title: 'Data Nilai',
                                    store: 'JsonStoreNilai',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            width: '5%',
                                            dataIndex: 'NoNilai_',
                                            text: 'No'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '5%',
                                            dataIndex: 'Nis_',
                                            text: 'Nis'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '25%',
                                            dataIndex: 'NamaSiswa_',
                                            text: 'Nama'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '10%',
                                            dataIndex: 'NamaKelas_',
                                            text: 'Kelas'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '15%',
                                            dataIndex: 'NamaMapel_',
                                            text: 'Mata Pelajaran'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '5%',
                                            dataIndex: 'Semester_',
                                            text: 'Semester'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '5%',
                                            dataIndex: 'Tugas1_',
                                            text: 'Tugas 1'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '5%',
                                            dataIndex: 'Tugas2_',
                                            text: 'Tugas 2'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '5%',
                                            dataIndex: 'Tugas3_',
                                            text: 'Tugas 3'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '5%',
                                            dataIndex: 'Uts_',
                                            text: 'UTS'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '5%',
                                            dataIndex: 'Uas_',
                                            text: 'UAS'
                                        },
                                        {
                                            xtype: 'datecolumn',
                                            width: '10%',
                                            dataIndex: 'Tgl_',
                                            text: 'Tanggal'
                                        }
                                    ],
                                    viewConfig: {
                                        itemId: 'GridViewNilai'
                                    },
                                    dockedItems: [
                                        {
                                            xtype: 'pagingtoolbar',
                                            dock: 'bottom',
                                            itemId: 'PagingToolbarNilai',
                                            width: 360,
                                            displayInfo: true,
                                            store: 'JsonStoreNilai'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'siswaPanel',
                            bodyCls: 'background',
                            title: '',
                            items: [
                                {
                                    xtype: 'container',
                                    cls: 'title-page',
                                    height: 90,
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            margins: '0, 0, 0, 10',
                                            cls: 'title-text',
                                            text: 'SISWA'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    margin: '20, 0, 0, 0',
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle',
                                        pack: 'center'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            margins: '10, 10, 10, 10',
                                            cls: 'btnTambah',
                                            itemId: 'btnTambahSiswa',
                                            maxWidth: 100,
                                            text: 'Tambah'
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            margins: '10, 10, 10, 10',
                                            cls: 'btnEdit',
                                            disabled: true,
                                            itemId: 'btnEditSiswa',
                                            maxWidth: 100,
                                            text: 'Edit'
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            margins: '10, 10, 10, 10',
                                            cls: 'btnHapus',
                                            disabled: true,
                                            itemId: 'btnHapusSiswa',
                                            maxWidth: 100,
                                            text: 'Hapus'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    margin: '20, 0, 0, 0',
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle'
                                    },
                                    items: [
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            margins: '10, 10, 10, 10',
                                            cls: 'btnRefresh',
                                            itemId: 'btnRefreshSiswa',
                                            maxWidth: 100,
                                            minWidth: 100,
                                            text: 'Refresh'
                                        },
                                        {
                                            xtype: 'textfield',
                                            margins: '10, 10, 10, 10',
                                            itemId: 'srcNamaSiswa',
                                            fieldLabel: 'Nama',
                                            labelWidth: 45
                                        },
                                        {
                                            xtype: 'combobox',
                                            margins: '10, 10, 10, 0',
                                            itemId: 'srcKelasSiswa',
                                            fieldLabel: 'Kelas',
                                            labelWidth: 40,
                                            emptyText: 'Pilih Kelas',
                                            editable: false,
                                            displayField: 'NamaKelas_',
                                            store: 'JsonStoreKelas',
                                            valueField: 'IDKelas_'
                                        },
                                        {
                                            xtype: 'button',
                                            flex: 1,
                                            margins: '10, 10, 10, 10',
                                            cls: 'btnCetak',
                                            itemId: 'btnCetakSiswa',
                                            maxWidth: 130,
                                            minWidth: 100,
                                            width: 100,
                                            text: 'Cetak Daftar Siswa'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'gridpanel',
                                    itemId: 'tabelSiswa',
                                    title: 'Data Siswa',
                                    store: 'JsonStoreSiswa',
                                    columns: [
                                        {
                                            xtype: 'gridcolumn',
                                            width: '5%',
                                            dataIndex: 'NoSiswa_',
                                            text: 'No'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '10%',
                                            dataIndex: 'Nis_',
                                            text: 'Nis'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '25%',
                                            dataIndex: 'NamaSiswa_',
                                            text: 'Nama'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '10%',
                                            dataIndex: 'NamaKelas_',
                                            text: 'Kelas'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '20%',
                                            dataIndex: 'NamaJur_',
                                            text: 'Jurusan'
                                        },
                                        {
                                            xtype: 'gridcolumn',
                                            width: '30%',
                                            dataIndex: 'Alamat_',
                                            text: 'Alamat'
                                        }
                                    ],
                                    viewConfig: {
                                        itemId: 'GridViewSiswa'
                                    },
                                    dockedItems: [
                                        {
                                            xtype: 'pagingtoolbar',
                                            dock: 'bottom',
                                            itemId: 'PagingToolbarSiswa',
                                            width: 360,
                                            displayInfo: true,
                                            store: 'JsonStoreSiswa'
                                        }
                                    ]
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            itemId: 'kelasjurPanel',
                            bodyCls: 'background',
                            title: '',
                            items: [
                                {
                                    xtype: 'container',
                                    cls: 'title-page',
                                    height: 90,
                                    layout: {
                                        type: 'hbox',
                                        align: 'middle'
                                    },
                                    items: [
                                        {
                                            xtype: 'label',
                                            margins: '0, 0, 0, 10',
                                            cls: 'title-text',
                                            text: 'Kelas dan Jurusan'
                                        }
                                    ]
                                },
                                {
                                    xtype: 'container',
                                    height: '100%',
                                    width: '100%',
                                    layout: 'hbox',
                                    items: [
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            margins: '0, 10, 0, 0',
                                            width: '50%',
                                            layout: {
                                                type: 'vbox',
                                                align: 'center'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    maxHeight: 50,
                                                    width: 300,
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle',
                                                        pack: 'center'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            flex: 1,
                                                            margins: '10, 10, 10, 10',
                                                            cls: 'btnTambah',
                                                            itemId: 'btnTambahKelas',
                                                            text: 'Tambah'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            flex: 1,
                                                            margins: '10, 10, 10, 10',
                                                            cls: 'btnEdit',
                                                            disabled: true,
                                                            itemId: 'btnEditKelas',
                                                            text: 'Edit'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            flex: 1,
                                                            margins: '10, 10, 10, 10',
                                                            cls: 'btnHapus',
                                                            disabled: true,
                                                            itemId: 'btnHapusKelas',
                                                            text: 'Hapus'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'gridpanel',
                                                    flex: 1,
                                                    itemId: 'tabelKelas',
                                                    width: '100%',
                                                    title: 'Data Kelas',
                                                    store: 'JsonStoreKelas',
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            width: '10%',
                                                            dataIndex: 'NoKelas_',
                                                            text: 'No'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            width: '90%',
                                                            dataIndex: 'NamaKelas_',
                                                            text: 'Nama Kelas'
                                                        }
                                                    ],
                                                    viewConfig: {
                                                        itemId: 'GridViewKelas'
                                                    }
                                                }
                                            ]
                                        },
                                        {
                                            xtype: 'container',
                                            flex: 1,
                                            width: '50%',
                                            layout: {
                                                type: 'vbox',
                                                align: 'center'
                                            },
                                            items: [
                                                {
                                                    xtype: 'container',
                                                    flex: 1,
                                                    maxHeight: 50,
                                                    width: 300,
                                                    layout: {
                                                        type: 'hbox',
                                                        align: 'middle',
                                                        pack: 'center'
                                                    },
                                                    items: [
                                                        {
                                                            xtype: 'button',
                                                            flex: 1,
                                                            margins: '10, 10, 10, 10',
                                                            cls: 'btnTambah',
                                                            itemId: 'btnTambahJurusan',
                                                            text: 'Tambah'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            flex: 1,
                                                            margins: '10, 10, 10, 10',
                                                            cls: 'btnEdit',
                                                            disabled: true,
                                                            itemId: 'btnEditJurusan',
                                                            text: 'Edit'
                                                        },
                                                        {
                                                            xtype: 'button',
                                                            flex: 1,
                                                            margins: '10, 10, 10, 10',
                                                            cls: 'btnHapus',
                                                            disabled: true,
                                                            itemId: 'btnHapusJurusan',
                                                            text: 'Hapus'
                                                        }
                                                    ]
                                                },
                                                {
                                                    xtype: 'gridpanel',
                                                    flex: 1,
                                                    itemId: 'tabelJurusan',
                                                    width: '100%',
                                                    title: 'Data Jurusan',
                                                    store: 'JsonStoreJurusan',
                                                    columns: [
                                                        {
                                                            xtype: 'gridcolumn',
                                                            width: '10%',
                                                            dataIndex: 'NoJur_',
                                                            text: 'No'
                                                        },
                                                        {
                                                            xtype: 'gridcolumn',
                                                            width: '90%',
                                                            dataIndex: 'NamaJur_',
                                                            text: 'Nama Jurusan'
                                                        }
                                                    ],
                                                    viewConfig: {
                                                        itemId: 'GridViewJurusan'
                                                    }
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ]
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    },

    onMenuClick: function(menu, item, e, eOpts) {
        location.hash = item.itemId;
    }

});