/*
 * File: app/view/window_siswa.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SistemInformasiNilai.view.window_siswa', {
    extend: 'Ext.window.Window',
    alias: 'widget.window_siswa',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.form.field.Number',
        'Ext.form.field.TextArea',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    height: 300,
    width: 400,
    title: 'Window Siswa',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    title: '',
                    items: [
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            fieldLabel: 'Label',
                            name: 'IDSiswa_'
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            fieldLabel: 'NIS',
                            name: 'Nis_',
                            minValue: 0
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Nama',
                            name: 'NamaSiswa_'
                        },
                        {
                            xtype: 'textareafield',
                            anchor: '100%',
                            fieldLabel: 'Alamat',
                            name: 'Alamat_'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Kelas',
                            name: 'IDKelas_',
                            blankText: 'Pilih Kelas',
                            emptyText: 'Pilih Kelas',
                            editable: false,
                            displayField: 'NamaKelas_',
                            store: 'JsonStoreKelas',
                            valueField: 'IDKelas_'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Jurusan',
                            name: 'IDJur_',
                            emptyText: 'Pilih Jurusan',
                            editable: false,
                            displayField: 'NamaJur_',
                            store: 'JsonStoreJurusan',
                            valueField: 'IDJur_'
                        }
                    ]
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'button',
                            flex: 0,
                            cls: 'btnWindowBatal',
                            itemId: 'btnWindowSiswaBatal',
                            style: '{\n    background: #ff2d55;\n    border: none;\n}',
                            text: 'Batal'
                        },
                        {
                            xtype: 'button',
                            flex: 0,
                            cls: 'btnWindowBatal',
                            itemId: 'btnWindowSiswaSimpan',
                            style: '{\n    background: #4cd964;\n    border: none;\n}',
                            text: 'Simpan'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});