/*
 * File: app/view/window_nilai.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SistemInformasiNilai.view.window_nilai', {
    extend: 'Ext.window.Window',
    alias: 'widget.window_nilai',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.form.field.Number',
        'Ext.form.field.Display',
        'Ext.form.field.ComboBox',
        'Ext.button.Button'
    ],

    height: 360,
    width: 421,
    title: 'Window Nilai',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    title: '',
                    items: [
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            fieldLabel: 'Label',
                            name: 'IDNilai_'
                        },
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            itemId: 'txtIdSiswa',
                            fieldLabel: 'Label',
                            name: 'IDSiswa_'
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            itemId: 'srcNisSiswa',
                            maxWidth: 210,
                            fieldLabel: 'NIS',
                            labelWidth: 120,
                            name: 'Nis_',
                            minValue: 0
                        },
                        {
                            xtype: 'displayfield',
                            anchor: '100%',
                            itemId: 'txtNamaSiswa',
                            fieldLabel: 'Nama',
                            labelWidth: 120,
                            name: 'NamaSiswa_',
                            value: 'Nama Siswa'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            fieldLabel: 'Mata Pelajaran',
                            labelWidth: 120,
                            name: 'IDMapel_',
                            emptyText: 'Pilih Mata Pelajaran',
                            editable: false,
                            displayField: 'NamaMapel_',
                            store: 'JsonStoreMapel',
                            valueField: 'IDMapel_'
                        },
                        {
                            xtype: 'combobox',
                            anchor: '100%',
                            maxWidth: 260,
                            fieldLabel: 'Semester',
                            labelWidth: 120,
                            name: 'Semester_',
                            emptyText: 'Pilih Semester',
                            editable: false,
                            displayField: 'Semester_',
                            queryMode: 'local',
                            store: 'JsonStoreSemester',
                            valueField: 'Semester_'
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            maxWidth: 190,
                            fieldLabel: 'Tugas 1',
                            labelWidth: 120,
                            name: 'Tugas1_',
                            maxValue: 100,
                            minValue: 0
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            maxWidth: 190,
                            fieldLabel: 'Tugas 2',
                            labelWidth: 120,
                            name: 'Tugas2_',
                            maxValue: 100,
                            minValue: 0
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            maxWidth: 190,
                            fieldLabel: 'Tugas 3',
                            labelWidth: 120,
                            name: 'Tugas3_',
                            maxValue: 100,
                            minValue: 0
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            maxWidth: 190,
                            fieldLabel: 'UTS',
                            labelWidth: 120,
                            name: 'Uts_',
                            maxValue: 100,
                            minValue: 0
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            maxWidth: 190,
                            fieldLabel: 'UAS',
                            labelWidth: 120,
                            name: 'Uas_',
                            maxValue: 100,
                            minValue: 0
                        }
                    ]
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'button',
                            flex: 0,
                            cls: 'btnWindowBatal',
                            itemId: 'btnWindowNilaiBatal',
                            style: '{\n    background: #ff2d55;\n    border: none;\n}',
                            text: 'Batal'
                        },
                        {
                            xtype: 'button',
                            flex: 0,
                            cls: 'btnWindowBatal',
                            itemId: 'btnWindowNilaiSimpan',
                            style: '{\n    background: #4cd964;\n    border: none;\n}',
                            text: 'Simpan'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});