/*
 * File: app/view/window_mapel.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SistemInformasiNilai.view.window_mapel', {
    extend: 'Ext.window.Window',
    alias: 'widget.window_mapel',

    requires: [
        'Ext.form.Panel',
        'Ext.form.field.Hidden',
        'Ext.form.field.Number',
        'Ext.button.Button'
    ],

    height: 152,
    width: 400,
    title: 'Window Mata Pelajaran',
    modal: true,

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'form',
                    bodyPadding: 10,
                    title: '',
                    items: [
                        {
                            xtype: 'hiddenfield',
                            anchor: '100%',
                            fieldLabel: 'Label',
                            name: 'IDMapel_'
                        },
                        {
                            xtype: 'textfield',
                            anchor: '100%',
                            fieldLabel: 'Mata Pelajaran',
                            labelWidth: 120,
                            name: 'NamaMapel_'
                        },
                        {
                            xtype: 'numberfield',
                            anchor: '100%',
                            maxWidth: 190,
                            fieldLabel: 'KKM',
                            labelWidth: 120,
                            name: 'Kkm_',
                            maxValue: 80,
                            minValue: 0
                        }
                    ]
                },
                {
                    xtype: 'container',
                    layout: {
                        type: 'hbox',
                        align: 'stretch',
                        pack: 'end'
                    },
                    items: [
                        {
                            xtype: 'button',
                            flex: 0,
                            cls: 'btnWindowBatal',
                            itemId: 'btnWindowMapelBatal',
                            style: '{\n    background: #ff2d55;\n    border: none;\n}',
                            text: 'Batal'
                        },
                        {
                            xtype: 'button',
                            cls: 'btnWindowSimpan',
                            itemId: 'btnWindowMapelSimpan',
                            style: '{\n    background: #4cd964;\n    border: none;\n}',
                            text: 'Simpan'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});