/*
 * File: app/model/modelNilai.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SistemInformasiNilai.model.modelNilai', {
    extend: 'Ext.data.Model',

    requires: [
        'Ext.data.Field'
    ],

    fields: [
        {
            name: 'NoNilai_'
        },
        {
            name: 'IDNilai_'
        },
        {
            name: 'IDSiswa_'
        },
        {
            name: 'IDMapel_'
        },
        {
            name: 'Semester_'
        },
        {
            name: 'Tugas1_'
        },
        {
            name: 'Tugas2_'
        },
        {
            name: 'Tugas3_'
        },
        {
            name: 'Uts_'
        },
        {
            name: 'Uas_'
        },
        {
            name: 'Tgl_'
        },
        {
            name: 'Nis_'
        },
        {
            name: 'NamaSiswa_'
        },
        {
            name: 'NamaMapel_'
        },
        {
            name: 'IDKelas_'
        },
        {
            name: 'NamaKelas_'
        }
    ]
});