/*
 * File: app/controller/homeController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SistemInformasiNilai.controller.homeController', {
    extend: 'Ext.app.Controller',

    onPanelShow: function(component, eOpts) {
        //value
        Ext.Ajax.request({
            url: 'api/home/dataHome.php',
            success: function(response) {
                console.log(response.responseText);
                response = Ext.decode(response.responseText);
                var jmlhKelas = response.ValueKelas_;
                var jmlhJur = response.ValueJur_;
                var jmlhMapel = response.ValueMapel_;
                var jmlhSiswa = response.ValueSiswa_;

                Ext.ComponentQuery.query('#txtValueKelas')[0].setText(jmlhKelas);
                Ext.ComponentQuery.query('#txtValueJurusan')[0].setText(jmlhJur);
                Ext.ComponentQuery.query('#txtValueMapel')[0].setText(jmlhMapel);
                Ext.ComponentQuery.query('#txtValueSiswa')[0].setText(jmlhSiswa);
            }
        });

        //chart
        // Ext.getStore('StoreChartHome').load();
        Ext.getStore('StoreChartColumn').load();
        Ext.getStore('StoreChartPie').load();
        Ext.getStore('JsonStoreMapel').load();
    },

    onGridpanelSelectionChange: function(model, selected, eOpts) {
            Ext.ComponentQuery.query('#btnEditMapel')[0].setDisabled(false);
            Ext.ComponentQuery.query('#btnHapusMapel')[0].setDisabled(false);
    },

    onBtnRefreshMapel: function(button, e, eOpts) {
        Ext.ComponentQuery.query('#tabelMapel')[0].getSelectionModel().clearSelections();
        Ext.ComponentQuery.query('#btnEditMapel')[0].setDisabled(true);
        Ext.ComponentQuery.query('#btnHapusMapel')[0].setDisabled(true);
        Ext.getStore('JsonStoreMapel').load();
    },

    onBtnTambahMapel: function(button, e, eOpts) {
        Ext.widget('window_mapel').show();
    },

    onBtnEditMapel: function(button, e, eOpts) {
        var win = Ext.widget('window_mapel').show();
        var grid = Ext.ComponentQuery.query('#tabelMapel')[0];
        var selection = grid.getSelectionModel().getSelection()[0];
        win.down('form').loadRecord(selection);
        win.show();
    },

    onBtnHapusMapel: function(button, e, eOpts) {
        var hapus = function(btn) {
            if(btn == 'yes'){
                var grid = Ext.ComponentQuery.query('#tabelMapel')[0];
                var selection = grid.getSelectionModel().getSelection()[0];
                var id = selection.get('IDMapel_');

                if(selection) {
                    Ext.Ajax.request({
                        url:'api/mapel/hapusMapel.php',
                        params:{
                            IDMapel_:id
                        },
                        success:function(response, opts) {
                            response = Ext.decode(response.responseText);
                            if(response.success){
                                Ext.ComponentQuery.query('#tabelMapel')[0].getSelectionModel().clearSelections();
                                Ext.ComponentQuery.query('#btnEditMapel')[0].setDisabled(true);
                                Ext.ComponentQuery.query('#btnHapusMapel')[0].setDisabled(true);
                                Ext.getStore('JsonStoreMapel').load();
                                SistemInformasiNilai.app.getController('homeController').onPanelShow();
                            }else{
                                 Ext.MessageBox.show({
                                     title:'Peringatan',
                                     msg:response.message,
                                     buttons:Ext.MessageBox.OK,
                                     icon:Ext.MessageBox.INFO
                                 });
                            }
                        }
                    });
                }
            }
        };
        Ext.MessageBox.show({
            title:'Peringatan hapus',
            msg:"Apa yakin?",
            buttons: Ext.MessageBox.YESNO,
            icon:Ext.MessageBox.QUESTION,
            fn:hapus
        });

    },

    onBtnWindowMapelBatal: function(button, e, eOpts) {
        button.up('window').close();
    },

    onBtnWindowMapelSimpan: function(button, e, eOpts) {
            var win = button.up('window');
            var form = win.down('form');

            if(form.isValid()) {
                form.submit({
                url:'api/mapel/simpanMapel.php',
                success:function(a, response){
                    console.log(a);
                    console.log(response);
                    win.close();
                    Ext.MessageBox.show({
                                title:"Berhasil",
                                msg:response.result.message,
                                icon:Ext.MessageBox.INFO
                            });

                    Ext.ComponentQuery.query('#tabelMapel')[0].getSelectionModel().clearSelections();
                    Ext.ComponentQuery.query('#btnEditMapel')[0].setDisabled(true);
                    Ext.ComponentQuery.query('#btnHapusMapel')[0].setDisabled(true);
                    Ext.getStore('JsonStoreMapel').load();
                    SistemInformasiNilai.app.getController('homeController').onPanelShow();
                },
                failure:function(a, response) {
                    //console.log("gagal");
                    Ext.MessageBox.show({
                        title:"Gagal",
                        msg:response.result.message,
                        icon:Ext.MessageBox.INFO
                    });
                }
            });
            }

    },

    init: function(application) {
        this.control({
            "#homePanel": {
                show: this.onPanelShow
            },
            "#tabelMapel": {
                selectionchange: this.onGridpanelSelectionChange
            },
            "#btnRefreshMapel": {
                click: this.onBtnRefreshMapel
            },
            "#btnTambahMapel": {
                click: this.onBtnTambahMapel
            },
            "#btnEditMapel": {
                click: this.onBtnEditMapel
            },
            "#btnHapusMapel": {
                click: this.onBtnHapusMapel
            },
            "#btnWindowMapelBatal": {
                click: this.onBtnWindowMapelBatal
            },
            "#btnWindowMapelSimpan": {
                click: this.onBtnWindowMapelSimpan
            }
        });
    }

});
