/*
 * File: app/controller/jurusanController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SistemInformasiNilai.controller.jurusanController', {
    extend: 'Ext.app.Controller',

    onPanelShow: function(component, eOpts) {
        Ext.getStore('JsonStoreJurusan').load();
    },

    ontnTambahJurusan: function(button, e, eOpts) {
        Ext.widget('window_jurusan').show();
    },

    onBtnEditJurusan: function(button, e, eOpts) {
        var win = Ext.widget('window_jurusan').show();
        var grid = Ext.ComponentQuery.query('#tabelJurusan')[0];
        var selection = grid.getSelectionModel().getSelection()[0];

        win.down('form').loadRecord(selection);
        win.show();
    },

    onBtnHapusJurusan: function(button, e, eOpts) {
        var hapus = function(btn) {
            if(btn == 'yes'){
                var grid = Ext.ComponentQuery.query('#tabelJurusan')[0];
                var selection = grid.getSelectionModel().getSelection()[0];
                var id = selection.get('IDJur_');

                if(selection) {
                    Ext.Ajax.request({
                        url:'api/jurusan/hapusJurusan.php',
                        params:{
                            IDJur_:id
                        },
                        success:function(response, opts) {
                            response = Ext.decode(response.responseText);
                            if(response.success){
                                Ext.ComponentQuery.query('#tabelJurusan')[0].getSelectionModel().clearSelections();
                                Ext.ComponentQuery.query('#btnEditJurusan')[0].setDisabled(true);
                                Ext.ComponentQuery.query('#btnHapusJurusan')[0].setDisabled(true);
                                Ext.getStore('JsonStoreJurusan').load();
        //                         Ext.Ajax.request({
        //                             url: 'api/siswa/jumlahSiswa.php',
        //                             success: function(response) {
        //                                 console.log(response.responseText);
        //                                 response = Ext.decode(response.responseText);
        //                                 console.log(response.message);
        //                                 var jumlah = response.message;
        //                                 Ext.ComponentQuery.query("#bykSiswa")[0].setText(jumlah);
        //                             }
        //                         });
                            }else{
                                 Ext.MessageBox.show({
                                     title:'Peringatan',
                                     msg:response.message,
                                     buttons:Ext.MessageBox.OK,
                                     icon:Ext.MessageBox.INFO
                                 });
                            }
                        }
                    });
                }
            }
        };
        Ext.MessageBox.show({
            title:'Peringatan hapus',
            msg:"Apa yakin?",
            buttons: Ext.MessageBox.YESNO,
            icon:Ext.MessageBox.QUESTION,
            fn:hapus
        });

    },

    onGridpanelSelectionChange: function(model, selected, eOpts) {
        Ext.ComponentQuery.query('#btnEditJurusan')[0].setDisabled(false);
        Ext.ComponentQuery.query('#btnHapusJurusan')[0].setDisabled(false);

        Ext.ComponentQuery.query('#tabelKelas')[0].getSelectionModel().clearSelections();
        Ext.ComponentQuery.query('#btnEditKelas')[0].setDisabled(true);
        Ext.ComponentQuery.query('#btnHapusKelas')[0].setDisabled(true);
        Ext.getStore('JsonStoreKelas').load();
    },

    onBtnWindowJurusanBatal: function(button, e, eOpts) {
        button.up('window').close();
    },

    onBtnWindowJurusanSimpan: function(button, e, eOpts) {
        var win = button.up('window');
        var form = win.down('form');

        if(form.isValid()) {
            form.submit({
                url:'api/jurusan/simpanJurusan.php',
                success:function(a, response){
                    console.log(a);
                    console.log(response);
                    win.close();
                    Ext.MessageBox.show({
                        title:"Berhasil",
                        msg:response.result.message,
                        icon:Ext.MessageBox.INFO
                    });

                    Ext.ComponentQuery.query('#tabelJurusan')[0].getSelectionModel().clearSelections();
                    Ext.ComponentQuery.query('#btnEditJurusan')[0].setDisabled(true);
                    Ext.ComponentQuery.query('#btnHapusJurusan')[0].setDisabled(true);
                    Ext.getStore('JsonStoreJurusan').load();
                },
                failure:function(a, response) {
                    //console.log("gagal");
                    Ext.MessageBox.show({
                        title:"Gagal",
                        msg:response.result.message,
                        icon:Ext.MessageBox.INFO
                    });
                }
            });
        }

    },

    init: function(application) {
        this.control({
            "#kelasjurPanel": {
                show: this.onPanelShow
            },
            "#btnTambahJurusan": {
                click: this.ontnTambahJurusan
            },
            "#btnEditJurusan": {
                click: this.onBtnEditJurusan
            },
            "#btnHapusJurusan": {
                click: this.onBtnHapusJurusan
            },
            "#tabelJurusan": {
                selectionchange: this.onGridpanelSelectionChange
            },
            "#btnWindowJurusanBatal": {
                click: this.onBtnWindowJurusanBatal
            },
            "#btnWindowJurusanSimpan": {
                click: this.onBtnWindowJurusanSimpan
            }
        });
    }

});
