/*
 * File: app/controller/nilaiController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SistemInformasiNilai.controller.nilaiController', {
    extend: 'Ext.app.Controller',

    onPanelShow: function(component, eOpts) {
        Ext.getStore('JsonStoreNilai').load();
        Ext.ComponentQuery.query('#btnCetakNilai')[0].setVisible(false);
    },

    onGridpanelSelectionChange: function(model, selected, eOpts) {
            Ext.ComponentQuery.query('#btnEditNilai')[0].setDisabled(false);
            Ext.ComponentQuery.query('#btnHapusNilai')[0].setDisabled(false);
            Ext.ComponentQuery.query('#btnCetakNilai')[0].setVisible(true);
    },

    onBtnTambahNilai: function(button, e, eOpts) {
        Ext.widget('window_nilai').show();
    },

    onBtnEditNilai: function(button, e, eOpts) {
        var win = Ext.widget('window_nilai').show();
        var grid = Ext.ComponentQuery.query('#tabelNilai')[0];
        var selection = grid.getSelectionModel().getSelection()[0];
        win.down('form').loadRecord(selection);
        win.show();
        Ext.ComponentQuery.query('#srcNisSiswa')[0].setVisible(false);
    },

    onBtnHapusNilai: function(button, e, eOpts) {
        var hapus = function(btn) {
            if(btn == 'yes'){
                var grid = Ext.ComponentQuery.query('#tabelNilai')[0];
                var selection = grid.getSelectionModel().getSelection()[0];
                var id = selection.get('IDNilai_');

                if(selection) {
                    Ext.Ajax.request({
                        url:'api/nilai/hapusNilai.php',
                        params:{
                            IDNilai_:id
                        },
                        success:function(response, opts) {
                            response = Ext.decode(response.responseText);
                            if(response.success){
                                Ext.ComponentQuery.query('#tabelNilai')[0].getSelectionModel().clearSelections();
                                Ext.ComponentQuery.query('#btnEditNilai')[0].setDisabled(true);
                                Ext.ComponentQuery.query('#btnHapusNilai')[0].setDisabled(true);
                                Ext.ComponentQuery.query('#btnCetakNilai')[0].setVisible(false);
                                Ext.getStore('JsonStoreNilai').load();
                            }else{
                                 Ext.MessageBox.show({
                                     title:'Peringatan',
                                     msg:response.message,
                                     buttons:Ext.MessageBox.OK,
                                     icon:Ext.MessageBox.INFO
                                 });
                            }
                        }
                    });
                }
            }
        };
        Ext.MessageBox.show({
            title:'Peringatan hapus',
            msg:"Apa yakin?",
            buttons: Ext.MessageBox.YESNO,
            icon:Ext.MessageBox.QUESTION,
            fn:hapus
        });

    },

    onBtnRefreshNilai: function(button, e, eOpts) {
            var nama = Ext.ComponentQuery.query('#srcNamaNilai')[0];
            var kelas = Ext.ComponentQuery.query('#srcKelasNilai')[0];
            var semester = Ext.ComponentQuery.query('#srcSemesterNilai')[0];
            var mapel = Ext.ComponentQuery.query('#srcMapelNilai')[0];

            nama.reset();
            kelas.reset();
            semester.reset();
            mapel.reset();
            Ext.getStore('JsonStoreNilai').load();

            Ext.ComponentQuery.query('#tabelNilai')[0].getSelectionModel().clearSelections();
            Ext.ComponentQuery.query('#btnEditNilai')[0].setDisabled(true);
            Ext.ComponentQuery.query('#btnHapusNilai')[0].setDisabled(true);
            Ext.ComponentQuery.query('#btnCetakNilai')[0].setVisible(false);
    },

    onBtnWindowNilaiBatal: function(button, e, eOpts) {
        button.up('window').close();
    },

    onBtnWindowNilaiSimpan: function(button, e, eOpts) {
            var win = button.up('window');
            var form = win.down('form');

            if(form.isValid()) {
                form.submit({
                url:'api/nilai/simpanNilai.php',
                success:function(a, response){
                    console.log(a);
                    console.log(response);
                    win.close();
                    Ext.MessageBox.show({
                                title:"Berhasil",
                                msg:response.result.message,
                                icon:Ext.MessageBox.INFO
                            });

                    Ext.ComponentQuery.query('#tabelNilai')[0].getSelectionModel().clearSelections();
                    Ext.ComponentQuery.query('#btnEditNilai')[0].setDisabled(true);
                    Ext.ComponentQuery.query('#btnHapusNilai')[0].setDisabled(true);
                    Ext.ComponentQuery.query('#btnCetakNilai')[0].setVisible(false);
                    Ext.getStore('JsonStoreNilai').load();
                },
                failure:function(a, response) {
                    //console.log("gagal");
                    Ext.MessageBox.show({
                        title:"Gagal",
                        msg:response.result.message,
                        icon:Ext.MessageBox.INFO
                    });
                }
            });
            }
    },

    onSrcNamaNilai: function(field, e, eOpts) {
        var namaSiswa = Ext.ComponentQuery.query('#srcNamaNilai')[0].getValue();
        var kelasSiswa = Ext.ComponentQuery.query('#srcKelasNilai')[0].getValue();
        var mapelNilai = Ext.ComponentQuery.query('#srcMapelNilai')[0].getValue();
        var semesterNilai = Ext.ComponentQuery.query('#srcSemesterNilai')[0].getValue();

        if(e.keyCode == e.ENTER) {
            Ext.getStore('JsonStoreNilai').load({
                params:{
                    NamaSiswa_ : namaSiswa,
                    KelasSiswa_ : kelasSiswa,
                    MapelNilai_ : mapelNilai,
                    SemesterNilai_ : semesterNilai
                }
            });
            console.log(namaSiswa);

            Ext.ComponentQuery.query('#tabelNilai')[0].getSelectionModel().clearSelections();
            Ext.ComponentQuery.query('#btnEditNilai')[0].setDisabled(true);
            Ext.ComponentQuery.query('#btnHapusNilai')[0].setDisabled(true);
        }
    },

    onSrcKelasNilai: function(combo, records, eOpts) {
        var namaSiswa = Ext.ComponentQuery.query('#srcNamaNilai')[0].getValue();
        var kelasSiswa = Ext.ComponentQuery.query('#srcKelasNilai')[0].getValue();
        var mapelNilai = Ext.ComponentQuery.query('#srcMapelNilai')[0].getValue();
        var semesterNilai = Ext.ComponentQuery.query('#srcSemesterNilai')[0].getValue();

        Ext.getStore('JsonStoreNilai').load({
            params:{
                NamaSiswa_ : namaSiswa,
                KelasSiswa_ : kelasSiswa,
                MapelNilai_ : mapelNilai,
                SemesterNilai_ : semesterNilai
            }
        });

        console.log(semesterNilai);

        Ext.ComponentQuery.query('#tabelNilai')[0].getSelectionModel().clearSelections();
        Ext.ComponentQuery.query('#btnEditNilai')[0].setDisabled(true);
        Ext.ComponentQuery.query('#btnHapusNilai')[0].setDisabled(true);
    },

    onSrcMapelNilai: function(combo, records, eOpts) {
        var namaSiswa = Ext.ComponentQuery.query('#srcNamaNilai')[0].getValue();
        var kelasSiswa = Ext.ComponentQuery.query('#srcKelasNilai')[0].getValue();
        var mapelNilai = Ext.ComponentQuery.query('#srcMapelNilai')[0].getValue();
        var semesterNilai = Ext.ComponentQuery.query('#srcSemesterNilai')[0].getValue();

        Ext.getStore('JsonStoreNilai').load({
            params:{
                NamaSiswa_ : namaSiswa,
                KelasSiswa_ : kelasSiswa,
                MapelNilai_ : mapelNilai,
                SemesterNilai_ : semesterNilai
            }
        });

        console.log(semesterNilai);

        Ext.ComponentQuery.query('#tabelNilai')[0].getSelectionModel().clearSelections();
        Ext.ComponentQuery.query('#btnEditNilai')[0].setDisabled(true);
        Ext.ComponentQuery.query('#btnHapusNilai')[0].setDisabled(true);
    },

    onSrcSemesterNilai: function(combo, records, eOpts) {
        var namaSiswa = Ext.ComponentQuery.query('#srcNamaNilai')[0].getValue();
        var kelasSiswa = Ext.ComponentQuery.query('#srcKelasNilai')[0].getValue();
        var mapelNilai = Ext.ComponentQuery.query('#srcMapelNilai')[0].getValue();
        var semesterNilai = Ext.ComponentQuery.query('#srcSemesterNilai')[0].getValue();

        Ext.getStore('JsonStoreNilai').load({
            params:{
                NamaSiswa_ : namaSiswa,
                KelasSiswa_ : kelasSiswa,
                MapelNilai_ : mapelNilai,
                SemesterNilai_ : semesterNilai
            }
        });

        console.log(semesterNilai);

        Ext.ComponentQuery.query('#tabelNilai')[0].getSelectionModel().clearSelections();
        Ext.ComponentQuery.query('#btnEditNilai')[0].setDisabled(true);
        Ext.ComponentQuery.query('#btnHapusNilai')[0].setDisabled(true);
    },

    onSrcNisSiswa: function(field, e, eOpts) {
        var nisSiswa = Ext.ComponentQuery.query('#srcNisSiswa')[0].getValue();

        if(e.keyCode == e.ENTER) {
            Ext.Ajax.request({
                url: 'api/nilai/searchSiswa.php?nis='+nisSiswa,
                success: function(response) {
                    console.log(response.responseText);
                    response = Ext.decode(response.responseText);
                    console.log(response.id);
                    console.log(response.nama);
                    var idSiswa = response.id;
                    var namaSiswa = response.nama;
                    Ext.ComponentQuery.query("#txtIdSiswa")[0].setValue(idSiswa);
                    Ext.ComponentQuery.query("#txtNamaSiswa")[0].setValue(namaSiswa);
                }
            });
            console.log(nisSiswa);
        }
    },

    onBtnCetakNilai: function(button, e, eOpts) {
        var win = Ext.widget('window_detail').show();
        var grid = Ext.ComponentQuery.query('#tabelNilai')[0];
        var selection = grid.getSelectionModel().getSelection()[0];
        var id = selection.data.IDNilai_;

        console.log(id);

        Ext.getStore('StoreChartNilai').load({
            params:{
                idnilai : id
            }
        });

        // Ext.widget('window_detail').show();

        win.down('form').loadRecord(selection);
        win.show();
        Ext.ComponentQuery.query('#srcNisSiswa')[0].setVisible(false);

        Ext.getStore('StoreChartNilai').load();
    },

    onBtnCetakNilaiBatal: function(button, e, eOpts) {
        button.up('window').close();
    },

    onBtnCetakNilaiSimpan: function(button, e, eOpts) {
        var grid = Ext.ComponentQuery.query('#tabelNilai')[0];
        var selection = grid.getSelectionModel().getSelection()[0];
        var id = selection.data.IDNilai_;

        console.log(id);

        window.open('api/nilai/printNilai.php?idnilai='+id).window.print();
    },

    init: function(application) {
        this.control({
            "#nilaiPanel": {
                show: this.onPanelShow
            },
            "#tabelNilai": {
                selectionchange: this.onGridpanelSelectionChange
            },
            "#btnTambahNilai": {
                click: this.onBtnTambahNilai
            },
            "#btnEditNilai": {
                click: this.onBtnEditNilai
            },
            "#btnHapusNilai": {
                click: this.onBtnHapusNilai
            },
            "#btnRefreshNilai": {
                click: this.onBtnRefreshNilai
            },
            "#btnWindowNilaiBatal": {
                click: this.onBtnWindowNilaiBatal
            },
            "#btnWindowNilaiSimpan": {
                click: this.onBtnWindowNilaiSimpan
            },
            "#srcNamaNilai": {
                specialkey: this.onSrcNamaNilai
            },
            "#srcKelasNilai": {
                select: this.onSrcKelasNilai
            },
            "#srcMapelNilai": {
                select: this.onSrcMapelNilai
            },
            "#srcSemesterNilai": {
                select: this.onSrcSemesterNilai
            },
            "#srcNisSiswa": {
                specialkey: this.onSrcNisSiswa
            },
            "#btnCetakNilai": {
                click: this.onBtnCetakNilai
            },
            "#btnCetakNilaiBatal": {
                click: this.onBtnCetakNilaiBatal
            },
            "#btnCetakNilaiSimpan": {
                click: this.onBtnCetakNilaiSimpan
            }
        });
    }

});
