/*
 * File: app/controller/siswaController.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('SistemInformasiNilai.controller.siswaController', {
    extend: 'Ext.app.Controller',

    onPanelShow: function(component, eOpts) {
        Ext.getStore('JsonStoreSiswa').load();
        Ext.ComponentQuery.query('#btnCetakSiswa')[0].setVisible(false);
    },

    onBtnTambahSiswa: function(button, e, eOpts) {
        Ext.widget('window_siswa').show();
    },

    onGridpanelSelectionChange: function(model, selected, eOpts) {
            Ext.ComponentQuery.query('#btnEditSiswa')[0].setDisabled(false);
            Ext.ComponentQuery.query('#btnHapusSiswa')[0].setDisabled(false);
    },

    onBtnEditSiswa: function(button, e, eOpts) {
        var win = Ext.widget('window_siswa').show();
        var grid = Ext.ComponentQuery.query('#tabelSiswa')[0];
        var selection = grid.getSelectionModel().getSelection()[0];

        win.down('form').loadRecord(selection);
        win.show();
    },

    onBtnHapusSiswa: function(button, e, eOpts) {
        var hapus = function(btn) {
            if(btn == 'yes'){
                var grid = Ext.ComponentQuery.query('#tabelSiswa')[0];
                var selection = grid.getSelectionModel().getSelection()[0];
                var id = selection.get('IDSiswa_');

                if(selection) {
                    Ext.Ajax.request({
                        url:'api/siswa/hapusSiswa.php',
                        params:{
                            IDSiswa_:id
                        },
                        success:function(response, opts) {
                            response = Ext.decode(response.responseText);
                            if(response.success){
                                Ext.ComponentQuery.query('#tabelSiswa')[0].getSelectionModel().clearSelections();
                                Ext.ComponentQuery.query('#btnEditSiswa')[0].setDisabled(true);
                                Ext.ComponentQuery.query('#btnHapusSiswa')[0].setDisabled(true);
                                Ext.getStore('JsonStoreSiswa').load();
                            }else{
                                 Ext.MessageBox.show({
                                     title:'Peringatan',
                                     msg:response.message,
                                     buttons:Ext.MessageBox.OK,
                                     icon:Ext.MessageBox.INFO
                                 });
                            }
                        }
                    });
                }
            }
        };
        Ext.MessageBox.show({
            title:'Peringatan hapus',
            msg:"Apa yakin?",
            buttons: Ext.MessageBox.YESNO,
            icon:Ext.MessageBox.QUESTION,
            fn:hapus
        });

    },

    onBtnWindowSiswaBatal: function(button, e, eOpts) {
        button.up('window').close();
    },

    onBtnWindowSiswaSimpan: function(button, e, eOpts) {
        var win = button.up('window');
            var form = win.down('form');

            if(form.isValid()) {
                form.submit({
                url:'api/siswa/simpanSiswa.php',
                success:function(a, response){
                    console.log(a);
                    console.log(response);
                    win.close();
                    Ext.MessageBox.show({
                                title:"Berhasil",
                                msg:response.result.message,
                                icon:Ext.MessageBox.INFO
                            });

                    Ext.ComponentQuery.query('#tabelSiswa')[0].getSelectionModel().clearSelections();
                    Ext.ComponentQuery.query('#btnEditSiswa')[0].setDisabled(true);
                    Ext.ComponentQuery.query('#btnHapusSiswa')[0].setDisabled(true);
                    Ext.getStore('JsonStoreSiswa').load();
                },
                failure:function(a, response) {
                    //console.log("gagal");
                    Ext.MessageBox.show({
                        title:"Gagal",
                        msg:response.result.message,
                        icon:Ext.MessageBox.INFO
                    });
                }
            });
            }
    },

    onSrcNamaSiswa: function(field, e, eOpts) {
        var namaSiswa = Ext.ComponentQuery.query('#srcNamaSiswa')[0].getValue();
        var kelasSiswa = Ext.ComponentQuery.query('#srcKelasSiswa')[0].getValue();

        if(e.keyCode == e.ENTER) {
            Ext.getStore('JsonStoreSiswa').load({
                params:{
                    NamaSiswa_ : namaSiswa,
                    KelasSiswa_ : kelasSiswa
                }
            });
            console.log(kelasSiswa);

            Ext.ComponentQuery.query('#tabelSiswa')[0].getSelectionModel().clearSelections();
            Ext.ComponentQuery.query('#btnEditSiswa')[0].setDisabled(true);
            Ext.ComponentQuery.query('#btnHapusSiswa')[0].setDisabled(true);
        }
    },

    onSrcKelasSiswa: function(combo, records, eOpts) {
        Ext.ComponentQuery.query('#btnCetakSiswa')[0].setVisible(true);

        var namaSiswa = Ext.ComponentQuery.query('#srcNamaSiswa')[0].getValue();
        var kelasSiswa = Ext.ComponentQuery.query('#srcKelasSiswa')[0].getValue();

        Ext.getStore('JsonStoreSiswa').load({
            params:{
                NamaSiswa_ : namaSiswa,
                KelasSiswa_ : kelasSiswa
            }
        });

        console.log(kelasSiswa);

        Ext.ComponentQuery.query('#tabelSiswa')[0].getSelectionModel().clearSelections();
        Ext.ComponentQuery.query('#btnEditSiswa')[0].setDisabled(true);
        Ext.ComponentQuery.query('#btnHapusSiswa')[0].setDisabled(true);
    },

    onBtnRefreshSiswa: function(button, e, eOpts) {
            var nama = Ext.ComponentQuery.query('#srcNamaSiswa')[0];
            var kelas = Ext.ComponentQuery.query('#srcKelasSiswa')[0];

            nama.reset();
            kelas.reset();
            Ext.getStore('JsonStoreSiswa').load();

            Ext.ComponentQuery.query('#tabelSiswa')[0].getSelectionModel().clearSelections();
            Ext.ComponentQuery.query('#btnEditSiswa')[0].setDisabled(true);
            Ext.ComponentQuery.query('#btnHapusSiswa')[0].setDisabled(true);
            Ext.ComponentQuery.query('#btnCetakSiswa')[0].setVisible(false);
    },

    onBtnCetakSiswa: function(button, e, eOpts) {
        // window.print();

        var id = Ext.ComponentQuery.query('#srcKelasSiswa')[0].getValue();

        console.log(id);

        window.open('api/siswa/printSiswa.php?idkelas='+id).window.print();
    },

    init: function(application) {
        this.control({
            "#siswaPanel": {
                show: this.onPanelShow
            },
            "#btnTambahSiswa": {
                click: this.onBtnTambahSiswa
            },
            "#tabelSiswa": {
                selectionchange: this.onGridpanelSelectionChange
            },
            "#btnEditSiswa": {
                click: this.onBtnEditSiswa
            },
            "#btnHapusSiswa": {
                click: this.onBtnHapusSiswa
            },
            "#btnWindowSiswaBatal": {
                click: this.onBtnWindowSiswaBatal
            },
            "#btnWindowSiswaSimpan": {
                click: this.onBtnWindowSiswaSimpan
            },
            "#srcNamaSiswa": {
                specialkey: this.onSrcNamaSiswa
            },
            "#srcKelasSiswa": {
                select: this.onSrcKelasSiswa
            },
            "#btnRefreshSiswa": {
                click: this.onBtnRefreshSiswa
            },
            "#btnCetakSiswa": {
                click: this.onBtnCetakSiswa
            }
        });
    }

});
